### DISCUSSION TITLE
How to persist flink catalogs configuration?

### DISCUSSION THREAD

**Discussion by cutiechi** [apache/kyuubi#2158] [Q&A]
How to persist flink catalogs configuration?

**Comment by cutiechi** [comment]
My sql-client-defaults.yaml:
```yaml
catalogs:
  - name: hive_catalog
    type: iceberg
    catalog-type: hive
    uri: thrift://192.168.9.70:9083
    clients: 5
    property-version: 1
    warehouse: s3a://hadoop/user/hive/warehouse
```
