### DISCUSSION TITLE
What is the appropriate kyuubi config to to expose k8s svc via ingress?

### DISCUSSION THREAD

**Discussion by etheleon** [apache/kyuubi#4989] [Q&A]
I currently have Kyuubi deployed in my k8s cluster using helm. 

When I list services, I see these three. Also HA is not enabled.

```
kubectl get svc
NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
kyuubi-rest            ClusterIP   10.100.169.128   <none>        10099/TCP   79d
kyuubi-thrift-binary   ClusterIP   10.100.176.218   <none>        10009/TCP   79d
kyuubi-thrift-http     ClusterIP   10.100.219.7     <none>        10010/TCP   6d17h
```
**Qn**: How do I let users outside of the cluster connect to the `kyuubi-thrift-binary` endpoint?

**Background**
I would like to allow my team to connect to thrift endpoint from their macbooks instead of from their jupyter notebooks running in the cluster. Currently, we can connect from within the cluster by using cluster DNS ie. `kyuubi-thrift-binary.kyuubi`. 

I've set up a ingress using ingressclass created by nginx helm deployment. 

I see a couple of configs also I see by default if it's a k8s deployment, `kyuubi.frontend.connection.url.use.hostname` is set to `false`

| field | default | meaning | type | since |
| --- | --- | --- | --- | --- |
| kyuubi.frontend.thrift.binary.bind.host | <undefined> | Hostname or IP of the machine on which to run the thrift frontend service via the binary protocol. | string | 1.4.0
kyuubi.frontend.thrift.binary.bind.port | 10009 | Port of the machine on which to run the thrift frontend service via the binary protocol. | int | 1.4.0
kyuubi.frontend.thrift.binary.ssl.disallowed.protocols | SSLv2,SSLv3 | SSL versions to disallow for Kyuubi thrift binary frontend. | seq | 1.7.0
kyuubi.frontend.thrift.binary.ssl.enabled | false | Set this to true for using SSL encryption in thrift binary frontend server. | boolean | 1.7.0
kyuubi.frontend.thrift.binary.ssl.include.ciphersuites |   | A comma-separated list of include SSL cipher suite names for thrift binary frontend. | seq | 1.7.0

What should I set?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    argocd.argoproj.io/instance: kyuubi-stg
  name: kyuubi-internal
  namespace: kyuubi-stg
spec:
  ingressClassName: <my-ingress-class>
  rules:
  - host: <hostname>
    http:
      paths:
      - backend:
          service:
            name: kyuubi-thrift-binary
            port:
              number: 10009
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - <hostname>
    secretName: ingress-tls-internal-kyuubi
```
