### ISSUE TITLE
[HELM] Kyuubi server should bind Pod IP by default

### ISSUE THREAD

**Issue by pan3793** [apache/kyuubi#4557]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/kyuubi/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

Currently, the Helm charts explicitly set Kyuubi server binding to `localhost`, and if user enable HA in the meanwhile, Kyuubi server will register itself to ZK, and that causes the registered address is `localhost:<thrift_port>`.
```
kyuubi.frontend.bind.host=localhost
```

### How should we improve?

Is it possible to dynamically apply the POD IP on launching POD?
```
kyuubi.frontend.bind.host=<POD_IP>
```

Otherwise, we can simply remove `kyuubi.frontend.bind.host` in the template, when absent, Kyuubi server will find the first non-localhost host/ip to bind.

### Are you willing to submit PR?

- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by pan3793** [comment]
cc @dnskr @hddong, WDYT?

**Comment by zwangsheng** [comment]
+1 for binding pod ip, as for solution, we can consult [Expose Pod Information to Containers Through Environment Variables](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/).

**Comment by dnskr** [comment]
Is it possible to pass Kyuubi configs through cli arguments?
For example `bin/kyuubi run --conf kyuubi.frontend.bind.host=$(hostname -I)`.
If so, the following should work:
```yaml
      containers:
        - name: kyuubi-server
          command: ["/bin/bash", "-c", "bin/kyuubi run --conf kyuubi.frontend.bind.host=$(hostname -I)"]
          ...
```
or as mentioned above
```yaml
      containers:
        - name: kyuubi-server
          command: ["/bin/bash", "-c", "bin/kyuubi run --conf kyuubi.frontend.bind.host=$POD_IP"]
          env:
           - name: POD_IP
             valueFrom:
               fieldRef:
                 fieldPath: status.podIP
```
